"use client";

import { createContext, ReactNode, useContext, useEffect, useState } from "react";

export type Language = "tr" | "en";

type LanguageContextValue = {
  language: Language;
  setLanguage: (language: Language) => void;
  t: (text: string) => string;
};

const translations: Record<string, string> = {
  "Anasayfa": "Home",
  "Bildirimler": "Notifications",
  "Mesajlar": "Messages",
  "Çıkış": "Sign out",
  "Giriş Yap / Kayıt Ol": "Log in / Sign up",
  "Soru Oluştur": "Create a question",
  "1. Adım: Kart Temasını Seçin": "Step 1: Choose a card theme",
  "Devam Et: Detayları Gir ➡️": "Continue: Enter details ➡️",
  "2. Adım: Soru ve Detaylar": "Step 2: Question and details",
  "Gönderen Kişinin Adı:": "Sender name:",
  "Profil adın": "Your profile name",
  "Gönderici adı profilinden alınır.": "Your sender name comes from your profile.",
  "Hedef Kişinin Adı:": "Recipient name:",
  "Örn: Onun Adı": "e.g. Their name",
  "Sormak İstediğin Soru:": "Your question:",
  "Örn: Benimle yemeğe çıkar mısın?": "e.g. Would you like to go out for dinner with me?",
  "Buluşma konumu:": "Meeting location:",
  "Tarih:": "Date:",
  "Zaman:": "Time:",
  "Saat": "Hour",
  "Dakika": "Minute",
  "Seçilen saat:": "Selected time:",
  "Geri": "Back",
  "Devam Et: GIF Seç ➡️": "Continue: Choose a GIF ➡️",
  "3. Adım: Bir GIF Seçin": "Step 3: Choose a GIF",
  "Önizle & Paylaş 🚀": "Preview & Share 🚀",
  "Hazırlanıyor...": "Preparing...",
  "Kart yükleniyor...": "Loading card...",
  "Oturum kontrol ediliyor...": "Checking session...",
  "Kart oluşturmak ve bildirim alabilmek için önce profil oluşturup giriş yapmalısın.": "Create a profile and log in to make a card and receive notifications.",
  "Hedef kişinin adını yazmalısın.": "Enter the recipient's name.",
  "Soru alanı zorunludur.": "The question is required.",
  "Kart kaydedilemedi, kısa paylaşım bağlantısı oluşturulamadı.": "The card could not be saved, so a short share link could not be created.",
  "Düzenlemeye Dön": "Back to editing",
  "Bağlantıyı Kopyala & Paylaş": "Copy & share link",
  "Link Kopyalandı!": "Link copied!",
  "Bu soru sana özel olarak gönderildi!": "This question was sent just for you!",
  "Sen de Kendi Kartını Oluştur": "Create your own card",
  "soruyor:": "asks:",
  "Tema 1: Kaçan Hayır": "Theme 1: The Dodging No",
  "Tema 2: Israrcı Cevaplar": "Theme 2: Persistent Answers",
  "Tema 3: Küçülen Buton": "Theme 3: Shrinking Button",
  "Tema 4: Yer Değiştiren": "Theme 4: Swapping Buttons",
  "Tema 5: Işınlanan Buton": "Theme 5: Teleporting Button",
  "Tema 6: Şifreli Hayır": "Theme 6: Password-Protected No",
  "Tema 7: Geri Sayımlı": "Theme 7: Countdown",
  "Tema 8: Ters Psikoloji": "Theme 8: Reverse Psychology",
  "Tema 9: Parçalanan Buton": "Theme 9: Shattering Button",
  "Tema 10: Mıknatıs Evet": "Theme 10: Magnetic Yes",
  "Tema 11: Bulmacalı Hayır": "Theme 11: Riddle No",
  "Tema 12: Sürpriz Kazı-Kazan": "Theme 12: Surprise Scratch Card",
  "Hayır ❌": "No ❌",
  "Emin misin? 🧐": "Are you sure? 🧐",
  "Son kararın mı? 🥺": "Is that your final answer? 🥺",
  "Gerçekten mi? 💔": "Really? 💔",
  "Bir daha düşün bence... 💭": "Maybe think again... 💭",
  "Lütfen ama yaa! 🙏": "Please, come on! 🙏",
  "Bak üzülürüm ama 😢": "I'll be sad, you know 😢",
  "Sana kurabiye alırım? 🍪": "I'll buy you a cookie? 🍪",
  "Bunu yapamazsın! 🙈": "You can't do this! 🙈",
  "Kırdın beni... 💥": "You broke my heart... 💥",
  "Hâlâ hayır mı diyorsun? 😿": "Are you still saying no? 😿",
  "Kalbimi kırıyorsun amanın! 💘": "You're breaking my heart! 💘",
  "Bak valla küserim 😤": "I really will sulk 😤",
  "İnat etme artık lütfen ✨": "Please stop being stubborn ✨",
  "Şaka yapıyorsun herhalde? 🙃": "You must be joking? 🙃",
  "Bence bir kez daha düşün 🌟": "I think you should reconsider 🌟",
  "Aslında evet demek istiyorsun 😉": "You actually want to say yes 😉",
  "Pes ediyorum... Şaka şaka, EVET de! 🎉": "I give up... Just kidding, say YES! 🎉",
  "Evet! 💖": "Yes! 💖",
  "Kesinlikle Evet! ✨": "Absolutely yes! ✨",
  "Tabii ki! 🥰": "Of course! 🥰",
  "Mükemmel Fikir! 🚀": "Perfect idea! 🚀",
  "Kaçırılmaz! 🌟": "Can't miss it! 🌟",
  "Tabii ki de Evet! 🎈": "Of course, yes! 🎈",
  "Zaten bekliyordum! 🍕": "I was waiting for this! 🍕",
  "Hemen şimdi! ✈️": "Right now! ✈️",
  "Bileti kaptım! 🎫": "Ticket secured! 🎫",
  "Sonuna kadar Evet! 👑": "Yes, absolutely! 👑",
  "⏳ Kalan Süre:": "⏳ Time left:",
  "Hayır demek için süren doldu, Evet demek zorundasın!": "Time's up to say no. You have to say yes!",
  "🧩 Günün Bilmecesine Hoş Geldin:": "🧩 Welcome to the riddle of the day:",
  "💡 İpucu:": "💡 Hint:",
  "Cevabınız...": "Your answer...",
  "Tahmin Et": "Guess",
  "Hayır demek için süren doldu! Evet demek zorundasın!": "Time's up to say no! You have to say yes!",
  "💌 Göndericinden bir mesaj var: Evet de!": "💌 A message from the sender: Say yes!",
  "diyor ki: Evet de!": "says: Say yes!",
  "Harika, kabul edildi! ❤️": "Wonderful, accepted! ❤️",
  "Cevabın kaydedildi, harika bir tercih!": "Your answer was saved. Great choice!",
  "Tekrar kutla 🎊": "Celebrate again 🎊",
  "Tekrar kutla": "Celebrate again",
  "Kartına Evet cevabı geldi! 🎉": "Your card got a Yes! 🎉",
  "Kartlarına gelen yanıtlar burada görünür.": "Responses to your cards will appear here.",
  "Bildirimler yükleniyor...": "Loading notifications...",
  "Henüz bildirimin yok.": "You don't have any notifications yet.",
  "Mesajlar yükleniyor...": "Loading messages...",
  "Henüz mesajın yok.": "You don't have any messages yet.",
  "Anasayfaya dön": "Back home",
  "Kullanıcı adıyla bir arkadaşına doğrudan mesaj gönder.": "Send a direct message to a friend by username.",
  "Alıcının kullanıcı adı": "Recipient username",
  "Mesajın": "Your message",
  "Mesajını yaz...": "Write your message...",
  "Mesaj Gönder": "Send message",
  "Gönderiliyor...": "Sending...",
  "Gelen ve gönderilen mesajlar": "Inbox and sent messages",
  "Alıcı:": "To:",
  "Mesajın gönderildi.": "Message sent.",
  "Profilini aç": "Open your profile",
  "👋 Giriş Yap": "👋 Log in",
  "Hesabına giriş yaparak soru kartı göndermeye devam et.": "Log in to continue creating question cards.",
  "E-posta Adresi:": "Email address:",
  "Şifre:": "Password:",
  "İşleniyor...": "Working...",
  "Hesabın yok mu? Hemen kaydol": "Don't have an account? Sign up",
  "Profilini Oluştur": "Create your profile",
  "Cardasks deneyimini kişiselleştirmek için bilgilerini gir.": "Enter your details to personalize your Cardasks experience.",
  "Profil fotoğrafı seç": "Choose a profile photo",
  "İsteğe bağlı, en fazla 2 MB": "Optional, up to 2 MB",
  "Adın": "Your name",
  "Adını yaz": "Enter your name",
  "Kullanıcı adın": "Your username",
  "Kullanıcı adını yaz": "Enter a username",
  "E-posta adresin": "Your email address",
  "Şifren": "Your password",
  "En az 6 karakter": "At least 6 characters",
  "Profil oluşturuluyor...": "Creating profile...",
  "Profil Oluştur": "Create profile",
  "Zaten hesabın var mı?": "Already have an account?",
  "Giriş yap": "Log in",
  "Profil": "Profile",
  "Profil bilgilerini düzenle": "Edit profile details",
  "Fotoğrafı değiştir": "Change photo",
  "Ad": "Name",
  "Kullanıcı adı": "Username",
  "E-posta adresi": "Email address",
  "Vazgeç": "Cancel",
  "Kaydediliyor...": "Saving...",
  "Kaydet": "Save",
  "Çıkış yap": "Sign out",
  "Konum aranıyor...": "Searching locations...",
  "Konum adı bulunuyor...": "Finding place name...",
  "Konum seçildi.": "Location selected.",
  "Koordinat seçildi; konum adı bulunamadı.": "Coordinates selected; place name unavailable.",
  "Konum bulunamadı. Başka bir arama dene.": "No locations found. Try another search.",
  "Konum aranamadı. Haritaya tıklayarak seçebilirsin.": "Could not search. Click the map to select a location.",
  "Bu tarayıcı konum özelliğini desteklemiyor.": "This browser doesn't support geolocation.",
  "Mevcut konumun seçildi.": "Your current location was selected.",
  "Mevcut konum koordinat olarak seçildi.": "Your current coordinates were selected.",
  "Konum izni alınamadı. Haritadan bir nokta seçebilirsin.": "Location permission denied. Select a point on the map.",
  "Şehir, adres veya mekan ara": "Search a city, address, or place",
  "Ara": "Search",
  "Konumumu bul": "Find my location",
  "Konum arama sonuçları": "Location search results",
  "Temizle": "Clear",
  "Haritaya tıkla veya konum ara": "Click the map or search for a place",
  "Yaz günlerinin vazgeçilmez dostu...": "A summer-day favorite...",
  "Yavaş yürür ama yolu hep yarılar.": "It walks slowly but always gets there.",
  "Kırmızı renkli, sulu ve çok tatlı.": "Red, juicy, and very sweet.",
  "Masmavi dalgaları vardır.": "It has deep blue waves.",
  "Kış gecelerinde ısıtır.": "It keeps you warm on winter nights.",
  "Altında tekerlekleri vardır.": "It has wheels underneath.",
  "Gökyüzünde süzülür, insan taşır.": "It soars through the sky carrying people.",
  "Ağzımızın içinde yaşarlar.": "They live inside our mouths.",
  "Sırtında evini taşır.": "It carries its home on its back.",
  "Dikiş dikerken en büyük yardımcımızdır.": "It's an essential helper when sewing.",
  "✅ Link Kopyalandı!": "✅ Link copied!",
  "🔗 Bağlantıyı Kopyala & Paylaş": "🔗 Copy & share link",
  "🎉 Harika! Bu karta zaten \"Evet\" denildi ve gönderene bildirildi!": "🎉 Great! This card was already answered \"Yes\" and the sender was notified!",
  "✏️ Düzenlemeye Dön": "✏️ Back to editing",
  "✨ Sen de Kendi Kartını Oluştur": "✨ Create your own card",
  "🎯 Tema 1: Kaçan Hayır": "🎯 Theme 1: The Dodging No",
  "💬 Tema 2: Israrcı Cevaplar": "💬 Theme 2: Persistent Answers",
  "🔍 Tema 3: Küçülen Buton": "🔍 Theme 3: Shrinking Button",
  "🔀 Tema 4: Yer Değiştiren": "🔀 Theme 4: Swapping Buttons",
  "⚡ Tema 5: Işınlanan Buton": "⚡ Theme 5: Teleporting Button",
  "🔒 Tema 6: Şifreli Hayır": "🔒 Theme 6: Password-Protected No",
  "⏳ Tema 7: Geri Sayımlı": "⏳ Theme 7: Countdown",
  "🪞 Tema 8: Ters Psikoloji": "🪞 Theme 8: Reverse Psychology",
  "💥 Tema 9: Parçalanan Buton": "💥 Theme 9: Shattering Button",
  "🧲 Tema 10: Mıknatıs Evet": "🧲 Theme 10: Magnetic Yes",
  "🧩 Tema 11: Bulmacalı Hayır": "🧩 Theme 11: Riddle No",
  "🎁 Tema 12: Sürpriz Kazı-Kazan": "🎁 Theme 12: Surprise Scratch Card",
  "Kart kaydedildi yanıtı geçersiz: ": "Invalid card save response: ",
  "Kart kimliği alınamadı.": "Card ID was not returned.",
  "Kısa paylaşım linki oluşturulamadı. Kartı tekrar kaydetmeyi dene.": "Could not create a short share link. Try saving the card again.",
  "Kart oluşturuldu ancak kısa paylaşım bağlantısı oluşturulamadı.": "The card was created, but a short share link could not be created.",
  "Kartı kaydetmek için giriş yapmalısın.": "You need to log in to save a card.",
  "Evet!": "Yes!",
  "Hayır": "No",
  "Yükleniyor...": "Loading...",
  "🎉 Harika, kabul edildi! ❤️": "🎉 Wonderful, accepted! ❤️",
  "✨ ": "✨ ",
  "Bunun doğru tahmin edilmesi imkansız, en iyisi pes edip Evet de! 💖": "There's no way to guess this one. Best to give up and say Yes! 💖",
  "Cevabın yanlış ama bilemesen de pes et ve Evet de! 🎉": "That's not right, but give up and say Yes anyway! 🎉",
  "Çok yaklaştın ama yine de yanlış! Pes et ve Evet de! 😉": "So close, but still wrong! Give up and say Yes! 😉",
  "Bunu doğru tahmin etmenin imkanı yok, en iyisi pes edip Evet de! 💖": "There's no way to guess this one. Best to give up and say Yes! 💖",
  "Hayır bu değil! Pes edip doğrudan Evet butonuna basmaya ne dersin? ✨": "Nope, that's not it! How about giving up and pressing Yes? ✨",
  "Zekice bir tahmdi ama maalesef yanlış. Pes et ve Evet de! 🚀": "Clever guess, but it's wrong. Give up and say Yes! 🚀",
  "Bu bilmeceyi çözmek yerine kalbini açıp Evet de! 🥰": "Instead of solving this riddle, open your heart and say Yes! 🥰",
  "Hadi ama bu kadar olamaz! 🚁": "Come on, it can't be that hard! 🚁",
  "Tamam peki... ama yine de Evet de? 💖": "Okay then... but maybe say Yes anyway? 💖",
  "💖 Hayır deme, birlikte çok güzel vakit geçirebiliriz!": "💖 Don't say no, we could have a wonderful time together!",
  "✨ Bence kalbinin sesini dinleyip Evet demelisin!": "✨ I think you should listen to your heart and say Yes!",
  "🌟 Bu teklif, güzel bir anıya dönüşebilir!": "🌟 This could turn into a lovely memory!",
  "🥰 Seninle buluşmak beni gerçekten mutlu eder!": "🥰 Meeting you would make me really happy!",
  "🎉 Evet dersen bugün çok daha güzel olacak!": "🎉 Saying Yes would make today so much better!",
  "🍀 Bir şans ver, pişman olmayacağına eminim!": "🍀 Give it a chance. I'm sure you won't regret it!",
  "☕ Bir kahve eşliğinde sohbet etmeye ne dersin?": "☕ How about chatting over a cup of coffee?",
  "🚀 Hayır yerine küçük ve güzel bir Evet seç!": "🚀 Choose a sweet little Yes instead of No!",
  "💫 Seninle paylaşacak çok güzel şeylerim var!": "💫 I have so many lovely things to share with you!",
  "🌈 Bu buluşma yüzünü mutlaka gülümsetecek!": "🌈 This date is sure to put a smile on your face!",
  "🎁 En güzel sürpriz, Evet demen olabilir!": "🎁 The best surprise could be you saying Yes!",
  "💌 Seni görmek için sabırsızlanıyorum!": "💌 I can't wait to see you!",
  "🌸 Birlikte geçireceğimiz zaman çok özel olacak!": "🌸 Our time together will be special!",
  "🏆 Bu kez kalbini dinle ve Evet de!": "🏆 Listen to your heart this time and say Yes!",
  "🎈 Hadi, güzel bir maceraya birlikte başlayalım!": "🎈 Come on, let's start a lovely adventure together!",
  "Hayır Demek İçin Şifre Girin": "Enter the password to say no",
  "Bu işlem yetkilendirme gerektirir!": "This action requires authorization!",
  "Şifreniz...": "Your password...",
  "Hatalı Şifre! (Erişim Engellendi)": "Incorrect password! (Access denied)",
  "Dene": "Try",
  "Vazgeç (Evet De)": "Cancel (say Yes)",
  "Mekan:": "Place:",
  "Saat:": "Time:",
  "Değiştir": "Change",
  "Kartlarınıza gelen yanıtlar burada görünür.": "Responses to your cards will appear here.",
  "Profil fotoğrafı yüklenemedi: ": "Could not upload profile photo: ",
  "Profil fotoğrafı profiline bağlanamadı: ": "Could not attach profile photo to your profile: ",
  "Bu kullanıcı adı zaten alınmış. Lütfen başka bir kullanıcı adı seç.": "That username is already taken. Please choose another.",
  "Profil oluşturulamadı. Lütfen tekrar dene.": "Could not create profile. Please try again.",
  "Profilin oluşturuldu. Hoş geldin!": "Your profile is ready. Welcome!",
  "Kayıt tamamlandı ancak otomatik giriş yapılamadı. Supabase Auth ayarlarından e-posta doğrulamasını geçici olarak kapatmalısın.": "Sign-up is complete, but automatic login failed. Temporarily disable email confirmation in Supabase Auth settings.",
  "Profil fotoğrafı": "Profile photo",
  "Profil fotoğrafı önizlemesi": "Profile photo preview",
  "Bu kullanıcı adı zaten alınmış. Lütfen başka bir kullanıcı adı seç": "That username is already taken. Please choose another.",
  "Profil güncellenemedi. Lütfen tekrar dene.": "Could not update profile. Please try again.",
  "Profilin güncellendi. Yeni e-posta adresini etkinleştirmek için gelen doğrulama bağlantısını onayla.": "Your profile was updated. Confirm the verification link to activate your new email address.",
  "Bildirimler sorgusu zaman aşımına uğradı veya oturum okunamadı. Lütfen çıkış yapıp tekrar giriş yap.": "The notifications request timed out or the session could not be read. Please sign out and log in again.",
  "Mesaj gönderilemedi. Lütfen tekrar dene.": "Could not send message. Please try again.",
  "Mesajlar yüklenemedi. Lütfen sayfayı yenile.": "Could not load messages. Please refresh the page.",
  "Alıcı bulunamadı. Kullanıcı adını kontrol et.": "Recipient not found. Check the username.",
  "Kendine mesaj gönderemezsin.": "You can't send a message to yourself.",
  "Mesajın boş olamaz.": "Your message can't be empty.",
  "Hesap bulunamadı.": "Account not found.",
  "Giriş yapman gerekiyor.": "You need to log in.",
  "Şu an konum aranıyor...": "Searching for a location...",
  "Konum bilgisi bulunamadı.": "Location details not found.",
  "Kart yanıtı gönderilemedi.": "Could not submit the card response.",
  "Yanıt gönderilemedi, lütfen tekrar dene.": "Could not submit your response. Please try again.",
  "Kopyalandı!": "Copied!",
  "Arkadaşına Link At": "Share the link with a friend",
  "Bu kartta Evet yanıtı zaten kaydedildi.": "A Yes response has already been saved for this card.",
  "Bu kart zaten yanıtlandı.": "This card has already been answered.",
  "Senin için bir kart gönderdi!": "sent you a card!",
  "sana bir kart gönderdi!": "sent you a card!",
  "Evet yanıtı gönderildi!": "Your Yes response was sent!",
  "Bilinmeyen kullanıcı": "Unknown user",
  "Karşı tarafın kullanıcı adı": "Friend's username",
  "Alıcı kullanıcı adını yaz": "Enter the recipient's username",
  "Mesaj gönderilemedi: ": "Could not send message: ",
  "Bir hata oluştu. Lütfen tekrar dene.": "Something went wrong. Please try again.",
  "Sunucudan boş yanıt geldi.": "The server returned an empty response.",
  "Kart kaydedilemedi, kısa paylaşım bağlantısı oluşturulamadı:": "Could not save the card or create a short share link:",
  "Kart kaydedildi yanıtı geçersiz:": "Invalid response after saving the card:",
  "Kart kaydı başarısız:": "Card save failed:",
  "Beklenmeyen hata": "Unexpected error",
  "💌 Bu soru sana özel olarak gönderildi!": "💌 This question was sent just for you!",
  "sana bir kart gönderdi! 🃏": "sent you a card! 🃏",
  "Bakalım ne cevap vereceksin? 😉": "Let's see how you'll answer! 😉",
  "@ için özel kart": "A card for",
  "kez denendi 🏃": "tries 🏃",
  "Kesinlikle Evet! 😉": "Absolutely yes! 😉",
  "Şu an konum alınıyor...": "Getting your location...",
  "Konum":"Location",
  "Geçersiz istek.": "Invalid request.",
  "Bu bağlantı kart kimliği olmadan açılamaz.": "This link needs a card ID to open.",
  "Bu kart bulunamadı.": "This card could not be found.",
  "Veriler alınamadı. Lütfen tekrar deneyin.": "Could not load data. Please try again.",
  "Geçersiz kullanıcı adı.": "Invalid username.",
  "Günlük kart oluşturma sınırına ulaştın.": "You've reached the daily card creation limit.",
  "Bir şeyler ters gitti.": "Something went wrong.",
  "Kart oluşturulamadı.": "Could not create the card.",
  "Kullanıcı bulunamadı.": "User not found.",
  "Oturum bulunamadı.": "Session not found.",
  "Kayıt başarısız.": "Sign-up failed.",
  "Şifre en az 6 karakter olmalı.": "Password must be at least 6 characters.",
  "Kullanıcı adı en az 3 karakter olmalı.": "Username must be at least 3 characters.",
  "Bilinmeyen hata.": "Unknown error.",
  "Gündüzleri ayaküstü dolaşırım, geceleri sırt üstü uyurum. Beni ne kadar ısıtırsan, o kadar terlerim.": "I stand on my feet by day and sleep on my back at night. The more you heat me, the more I sweat.",
  "Uzaktan baktım bir taş, yanına vardım dört ayak bir baş.": "From afar I saw a stone; up close, four legs and one head.",
  "Çarşıdan aldım bir tane, eve geldim bin tane.": "I bought one at the market, but brought home a thousand.",
  "Karşıdan baktım bir biçim, ağzı var dili yok, içindeki su içilmez hiç.": "From afar it has a shape, a mouth but no tongue; its water is never for drinking.",
  "Ağzı var odun yutar, bacası var duman tutar.": "It has a mouth that swallows wood and a chimney that catches smoke.",
  "Uzun yassı, içine girilmez ama üstünde her şey taşınır.": "Long and flat, you can't get inside, but everything rides on top.",
  "Kanadı var kuş değil, boynuzu var koç değil.": "It has wings but isn't a bird, horns but isn't a ram.",
  "Biz biz idik, otuz iki kız idik, ezildik büzüldük, duvara dizildik.": "There were thirty-two of us; crushed and lined up against a wall.",
  "Kuru kök üstünde yeşilbaş, dünyayı dolaşır yavaş yavaş.": "A green head on a dry root, traveling the world ever so slowly.",
  "Bir küçücük milcik, içi dolu kancık.": "A tiny little thing, full of hooks inside.",
  "Lütfen JPG, PNG veya WebP formatında bir fotoğraf seç.": "Choose a photo in JPG, PNG, or WebP format.",
  "Fotoğraf en fazla 2 MB olabilir.": "The photo must be no larger than 2 MB.",
  "Geçerli bir e-posta adresi gir. Örnek: ad@ornek.com": "Enter a valid email address. Example: name@example.com",
  "Kullanıcı adı servisi hazır değil. Supabase profiles tablosunu oluşturmalısın.": "The username service isn't ready. Create the Supabase profiles table first.",
  "Bu e-posta adresi zaten kayıtlı. Giriş yapmayı deneyebilirsin.": "This email is already registered. Try logging in.",
  "Profil fotoğrafı yüklenemedi:": "Could not upload profile photo:",
  "Profil fotoğrafı profiline bağlanamadı:": "Could not attach profile photo to your profile:",
  "Bu kullanıcı adıyla kayıtlı bir profil bulunamadı.": "No profile found with that username.",
  "Kullanıcı": "User",
  "en alakalı konum bulundu. Birini seç.": "relevant locations found. Choose one.",
  "Gönderen": "Sender",
  "Gönderdiğin soru kartı kabul edildi.": "The question card you sent was accepted.",
  "soruna Evet yanıtı verdi:": "replied Yes to your question:",
  "🔗 Arkadaşına Link At": "🔗 Share the link with a friend",
  "Seçilen:": "Selected:",
  "ornek@mail.com": "name@example.com",
};

const LanguageContext = createContext<LanguageContextValue>({
  language: "tr",
  setLanguage: () => undefined,
  t: (text) => text,
});

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>("tr");

  useEffect(() => {
    const stored = window.localStorage.getItem("cardasks-language");
    if (stored === "en" || stored === "tr") setLanguageState(stored);
  }, []);

  useEffect(() => {
    document.documentElement.lang = language;
    document.title = language === "en" ? "Cardasks | Send a question" : "Cardasks ile soru gönder";
    window.localStorage.setItem("cardasks-language", language);
  }, [language]);

  const setLanguage = (next: Language) => setLanguageState(next);
  const t = (text: string) => language === "en" ? translations[text] || text : text;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
